spring:
  jpa:
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        default_schema: accounts
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: grp
    password: grp
  application:
    name: demo-project
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

server:
  port: 8081
  servlet:
    context-path: /demo-project